# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# TODO: Seperate into files

matches:
  # Simple text replacement
  - trigger: ";espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: ";no"
    replace: "❌"
  - trigger: ";yes"
    replace: "✅"
  - trigger: ";coin"
    replace: "🪙"
  - trigger: ";ada"
    replace: "₳"
  - trigger: ";tm"
    replace: "™"
  - trigger: ";thumbs"
    replace: "👍"
  - trigger: ";jira"
    replace: "[JIRA Ticket](https://nemetschek.atlassian.net/browse/$|$)"
  - trigger: ";bs"
    replace: "BBCLD-"
  - trigger: ";pe"
    replace: "PE-"
  - trigger: ";book"
    replace: "📘"
  - trigger: ";bolt"
    replace: "⚡️"
  - trigger: ";bug"
    replace: "🐛"
  - trigger: ";brain"
    replace: "🧠"
  - trigger: ";flip"
    replace: "(╯°□°)╯︵ ┻━┻"
  - trigger: ";think"
    replace: "🤔"
  - trigger: ";moon"
    replace: "🌙"
  - trigger: ";light"
    replace: "💡"
  - trigger: ";grin"
    replace: "😁"
  - trigger: ";dead"
    replace: "💀"

  - trigger: ";bird"
    replace: "🐦"
  - trigger: ";deg"
    replace: "°"

  - trigger: ";!"
    replace: "❗️"
  - trigger: ";pp"
    replace: "💢"
  - trigger: ";q "
    replace: "❓ "
  - trigger: ";raise"
    replace: "🙌"
  - trigger: ";pi"
    replace: "𝜋"
  - trigger: ";tau"
    replace: "𝜏"
  - trigger: ";people"
    replace: "👥"
  - trigger: ";person"
    replace: "👤"
  - trigger: ";poo"
    replace: "💩"
  - trigger: ";eyes"
    replace: "👀"
  - trigger: ";reload"
    replace: "🔁"

  # Arrows
  - trigger: ";up"
    replace: "↑"
  - trigger: ";down"
    replace: "↓"
  - trigger: ";left"
    replace: "←"
  - trigger: ";right"
    replace: "→"

  # Box
  - trigger: ";box"
    replace: "▢"

  # Dynamic
  # FIX: needs dynamic datetime
  # - trigger: ";dt "
  #   replace: "{YYYY}.{MM}.{DD} "

  # FIX: Run JS function on expansion
  # - trigger: ";eu "
    # replace: "[[{/JavaScript
    #   function makeid(length) {
    #     var result           = '';
    #     var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    #     var charactersLength = characters.length;
    #     for ( var i = 0; i < length; i++ ) {
    #       result += characters.charAt(Math.floor(Math.random() * charactersLength));
    #     }
    #     return result;
    #   }
    #   makeid(12)
    #   }{^}]]"

  - trigger: ";uuid"
    replace: "{{uuid}}"
    vars:
      - name: uuid
        type: shell
        params:
          cmd: "uuidgen"

  # Emotes
  - trigger: ";shrug"
    replace: "¯\\_(ツ)_/¯"

  # Colors
  - trigger: ";red"
    replace: "🔴"
  - trigger: ";yel"
    replace: "🟡"
  - trigger: ";gre"
    replace: "🟢"
  - trigger: ";ora"
    replace: "🟠"
  - trigger: ";gray"
    replace: "⚪️"
  - trigger: ";white"
    replace: "⚪️"
  - trigger: ";blue"
    replace: "🔵"
  - trigger: ";black"
    replace: "⚫️"

  - trigger: ";clip"
    replace: "{{clipb}}"
    vars:
      - name: "clipb"
        type: "clipboard"
